name = "ytcomment-mcp-server"
main = "src/cloudflare_worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

# Environment variables for the worker
[vars]
LOG_LEVEL = "info"
MCP_SERVER_NAME = "YouTube Comment Downloader"
PYTHONPATH = "/src"

# Development environment
[env.development]
name = "ytcomment-mcp-server-dev"

# Production environment  
[env.production]
name = "ytcomment-mcp-server-prod"